services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  minivault-api:
    build: ./src
    container_name: minivault-api
    environment:
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8080:8080"
    depends_on:
      - ollama

volumes:
  ollama:
